sample_benefits_1:
  file_name: sample_benefits_x_c.csv
  folder: 00_raw
  args:
    index_col: benefit_name

sample_benefits_2:
  file_name: sample_benefits_x_c_2.csv
  folder: 00_raw
  args:
    index_col: benefit_name

sample_beneficiary_1:
  file_name: sample_beneficiary_x_c.csv
  folder: 00_raw
  args:
    index_col: beneficiary_name

sample_beneficiary_2:
  file_name: sample_beneficiary_x_c_2.csv
  folder: 00_raw
  args:
    index_col: beneficiary_name

sample_beneficiary_pii:
  file_name: sample_beneficiary_pii.csv
  folder: 00_raw
  args:
    index_col: beneficiary_name

recommendation_comments:
  file_name: results_comments.csv
  folder: 04_modeloutput

recommendation_proximity:
  file_name: results_proximity.csv
  folder: 04_modeloutput

sample_beneficiary_scheme:
  file_name: sample_beneficiary_scheme.csv
  folder: 00_raw
  args:
    index_col: beneficiary_name

sample_impute_ref:
  file_name: sample_impute_reference.csv
  folder: 00_raw

key_impute_ref:
  file_name: key_impute_reference.csv
  folder: 00_raw

recommendation_full:
  file_name: results_full.csv
  folder: 04_modeloutput

bocw:
  file_name: Registered Data.csv
  folder: 00_raw

bocw_reg_trans:
  file_name: bocw_reg_beneficiary.csv
  folder: 01_preprocessed
  args:
    index_col: beneficiary_name

bocw_claims_raw:
  file_name: bocw_claims_data.csv
  folder: 00_raw

bocw_claims_trans:
  file_name: bocw_claims_beneficiary.csv
  folder: 01_preprocessed

key_benefits:
  file_name: key_benefits.csv
  folder: 00_raw
  args:
    index_col: benefit_name
