CREATE TABLE IF NOT EXISTS family_members (
    id VARCHAR(8),
    family_id VARCHAR(32),
    name VARCHAR(128),
    dob DATE NULL DEFAULT NULL,
    gender gen_enum,
    family_role role_enum,
    disadvantaged bool_unk_enum,
    pregnancy bool_unk_enum,
    job VARCHAR(256),
    jobType VARCHAR(128),
    in_educational_institute bool_unk_enum,
    education_level VARCHAR(64),
    prev_year_tenth bool_unk_enum,
    prev_year_twelfth bool_unk_enum,
    tenth_percentage_marks DECIMAL(5,2),
    twelfth_percentage_marks DECIMAL(5,2),
    tenth_top_ten bool_unk_enum,
    twelfth_top_ten bool_unk_enum,
    has_bocw_card bool_unk_enum,
    bocw_card_issue_date DATE NULL DEFAULT NULL,
    has_uow_card bool_unk_enum,
    uow_card_issue_date DATE NULL DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (family_id) REFERENCES families(id)
);
