CREATE TABLE family_members (
    id VARCHAR(8),
    family_id VARCHAR(8),
    dob DATE,
    gender ENUM('male', 'female', 'other'),
    family_role ENUM('grandparent', 'father', 'mother', 'child', 'in-law', 'other'),
    disadvantaged ENUM('true', 'false', 'unknown'),
    job VARCHAR(128),
    jobType VARCHAR(128),
    in_educational_institute ENUM('true', 'false', 'unknown'),
    education_level VARCHAR(64),
    prev_year_tenth ENUM('true', 'false', 'unknown'),
    prev_year_twelfth ENUM('true', 'false', 'unknown'),
    tenth_percentage_marks FLOAT(5,2),
    twelfth_percentage_marks FLOAT(5,2),
    tenth_top_ten ENUM('true', 'false', 'unknown'),
    twelfth_top_ten ENUM('true', 'false', 'unknown'),
    has_bocw_card ENUM('true', 'false', 'unknown'),
    bocw_card_issue_date DATE,
    has_uow_card ENUM('true', 'false', 'unknown'),
    uow_card_issue_date DATE,
    PRIMARY KEY (id),
    FOREIGN KEY (family_id) REFERENCES families(id)
);
