CREATE TABLE family_members (
    id VARCHAR(8),
    family_id VARCHAR(8),
    dob DATE,
    gender ENUM('male', 'female', 'other'),
    family_role ENUM('grandparent', 'father', 'mother', 'child', 'in-law', 'other'),
    disadvantaged boolean,
    job VARCHAR(128),
    jobType VARCHAR(128),
    in_educational_institute boolean,
    education_level VARCHAR(64),
    prev_year_tenth boolean,
    prev_year_twelfth boolean,
    tenth_percentage_marks FLOAT(5,2),
    twelfth_percentage_marks FLOAT(5,2),
    tenth_top_ten boolean,
    twelfth_top_ten boolean,
    has_bocw_card boolean,
    bocw_card_issue_date DATE,
    has_uow_card boolean,
    uow_card_issue_date DATE,
    PRIMARY KEY (id),
    FOREIGN KEY (family_id) REFERENCES families(id)
);